root: true
parserOptions:
  sourceType: module
  scmaFeatures:
    impliedStrict: True
rules:
  semi: 2
  no-console: 0
  no-unused-vars: 0
env:
  browser: true
  node: true
  es6: true
  jquery: true
extends: "eslint:recommended"